"""Remove DOGE address from Candidate model

Revision ID: 1b0c3db61d3b
Revises: c9cff959ef97
Create Date: 2024-09-16 17:07:05.707212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0c3db61d3b'
down_revision = 'c9cff959ef97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('doge_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doge_address', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
