"""Add youtube_snippet to Candidate model

Revision ID: 4519ad222d93
Revises: cf3d6e5e66a1
Create Date: 2024-09-17 21:55:15.379867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4519ad222d93'
down_revision = 'cf3d6e5e66a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btc_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('youtube_snippet', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('youtube_snippet')
        batch_op.drop_column('btc_address')

    # ### end Alembic commands ###
