"""Add btc_address and doge_address to Candidate model

Revision ID: b05c22fe73c8
Revises: 1b0c3db61d3b
Create Date: 2024-09-16 19:34:30.121853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05c22fe73c8'
down_revision = '1b0c3db61d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_candidate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('website', sa.TEXT(), nullable=True),
    sa.Column('social_media', sa.TEXT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=False),
    sa.Column('contact', sa.VARCHAR(length=100), nullable=False),
    sa.Column('photo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('average_rating', sa.FLOAT(), nullable=True),
    sa.Column('btc_address', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
