"""Add average_rating to Candidate model

Revision ID: b2512f3fe86f
Revises: b348256b5b1c
Create Date: 2024-09-13 03:37:36.228809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2512f3fe86f'
down_revision = 'b348256b5b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
