"""Add btc_address and doge_address to Candidate model

Revision ID: c9cff959ef97
Revises: b2512f3fe86f
Create Date: 2024-09-16 00:43:18.469059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cff959ef97'
down_revision = 'b2512f3fe86f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btc_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('doge_address', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_column('doge_address')
        batch_op.drop_column('btc_address')

    # ### end Alembic commands ###
