"""Add phone, website, and social_media to Candidate model

Revision ID: cb5cafb155fc
Revises: 8dc5c8e3eb21
Create Date: 2024-09-12 17:04:35.996164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5cafb155fc'
down_revision = '8dc5c8e3eb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('social_media', sa.Text(), nullable=True))
        batch_op.drop_column('education')
        batch_op.drop_column('skills')
        batch_op.drop_column('experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('education', sa.TEXT(), nullable=True))
        batch_op.drop_column('social_media')
        batch_op.drop_column('website')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
